# Generated by Django 4.0.3 on 2022-03-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
