# Generated by Django 4.0.3 on 2022-03-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ingredients_id_alter_recipes_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ingredients'),
        ),
    ]
