# Generated by Django 4.0.3 on 2022-03-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_ingredient_name_ingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
    ]
