# Generated by Django 4.0.3 on 2022-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
            ],
        ),
    ]
