# Generated by Django 4.0.3 on 2022-03-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
